language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
install:
  - cpanm JSON::PP Dist::Zilla
  - dzil authordeps --missing | cpanm -n || { cat ~/.cpanm/build.log ; false ; }
  - dzil listdeps --author --missing | cpanm -n || { cat ~/.cpanm/build.log ; false ; }
script:
  - dzil test --author --release
sudo: false
notifications:
  email: false
